## Ch-1.0 - PyTourch Fundamentals

In [ ]:
## import python modules/library
import torch
print(torch.__version__)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


1.13.1+cu116


### Introduction to Tensor

In [ ]:
## Introduction to Tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim, scalar.shape, scalar.dtype

(0, torch.Size([]), torch.int64)

In [ ]:
scalar.item() # Get back tensor as Python int

7

In [ ]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim, vector.shape, vector.dtype

(1, torch.Size([2]), torch.int64)

In [ ]:
# Matrix

matrix = torch.tensor([[7,8],
                        [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim, matrix.shape, matrix.dtype

(2, torch.Size([2, 2]), torch.int64)

In [ ]:
# Tensor

tensor1 = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
tensor1

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
tensor1.ndim, tensor1.shape, tensor1.dtype

(3, torch.Size([1, 3, 3]), torch.int64)

In [ ]:
tensor2 = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]],
                        
                        [[11,12,13],
                         [14,15,16],
                         [17,18,19]]])
tensor2

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]]])

In [ ]:
tensor2.ndim, tensor2.shape, tensor2.dtype

(3, torch.Size([2, 3, 3]), torch.int64)

### Random Tensors

Why random tensors?

Random tensors are important because the way neural network learns is that it start with random numbers and looks at data and then updates random numbers so model fits the data better. And this process is repeated utill model achieves ability to fit/predict the data with some accuracy using final updated random numbers.

In [ ]:
# Create a random tensor of size (3, 4)

random_tensor = torch.rand(size=(3,4))
random_tensor

tensor([[0.6931, 0.9836, 0.5706, 0.2903],
        [0.3961, 0.2068, 0.0309, 0.3096],
        [0.8584, 0.3492, 0.8236, 0.7502]])

In [ ]:
random_tensor.ndim, random_tensor.shape, random_tensor.dtype

(2, torch.Size([3, 4]), torch.float32)

In [ ]:
# Create a random tensor with simitlar shapre to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) ## height, width, color channels (R, G, B)

In [ ]:
random_image_size_tensor.ndim, random_image_size_tensor.shape, random_image_size_tensor.dtype

(3, torch.Size([224, 224, 3]), torch.float32)

### Tensor with Zeros and Ones

In [ ]:
# Create tensor with all zeros
zeros = torch.zeros(size=(4,5))
zeros, zeros.ndim, zeros.shape

In [ ]:
# Create tensor with all ones
ones = torch.ones(size=(4,5))
ones, ones.ndim, ones.shape

(tensor([[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]), 2, torch.Size([4, 5]))

### Creating range of tensor and tensor likes

In [ ]:
arange = torch.arange(start=0,end=20, step=1)
arange, arange.ndim, arange.shape

(tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19]), 1, torch.Size([20]))

In [ ]:
tensor_like = torch.zeros_like(input=arange)
tensor_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatype, shape and device:
**Note** : data type is one of the 3 big erros that you will run into deep learning in general.
1. Tensor is not correct datatype.
2. Tensor is not in correct shape.
3. Tensor is not on the correct device.

In [ ]:
tensor_ex = torch.tensor([3., 6., 9.], 
                            dtype=None,           # datatype of the tensor
                            device=None,          # which device is the tensor on
                            requires_grad=False)  # whehter or not to track gradients with this tensor's operations
tensor_ex, tensor_ex.dtype, tensor_ex.shape, tensor_ex.device

(tensor([3., 6., 9.]), torch.float32, torch.Size([3]), device(type='cpu'))

### Tensor Operations:

1. Addition
2. Subtraction
3. Multiplication
4. Division
5. Matrix Multiplication

 Note: you can also use in-build PyTorch functions for tensor operation.

In [ ]:
#addition
tensor = torch.tensor([1,2,4])
tensor + 10

tensor([11, 12, 14])

In [ ]:
# multiplication
tensor * 10

tensor([10, 20, 40])

In [ ]:
#subtract
tensor - 10

tensor([-9, -8, -6])

### Matrix/Tensor Mutliplication:

Two main ways:
1. Element-wise multiplication
2. Matrix multiplication or Dot product

In [ ]:
# Element-wise multiplication
tensor

tensor([1, 2, 4])

In [ ]:
tensor * tensor

tensor([ 1,  4, 16])

In [ ]:
# dot product - you can use `torch.matmul()` or `torch.dot()` function.
torch.matmul(tensor, tensor)

tensor(21)

In [ ]:
torch.dot(tensor, tensor)

tensor(21)

### Tensor aggregations: 
1. min
2. max
3. mean (only works with floating points)
4. sum


In [ ]:
torch.min(tensor)

tensor(1)

In [ ]:
tensor.min()

tensor(1)

In [ ]:
torch.max(tensor)

tensor(4)

In [ ]:
tensor.max()

tensor(4)

In [ ]:
torch.mean(tensor)  ## torch.mean() function requires tensor to be float32 datatype.

RuntimeError: ignored

In [ ]:
torch.mean(tensor.type(torch.float32))

tensor(2.3333)

In [ ]:
torch.sum(tensor)

tensor(7)

In [ ]:
tensor.sum()

tensor(7)

### Finding positional max and min of the tensor

In [ ]:
tensor_x = torch.arange(start=0,end=100)

In [ ]:
tensor_x.argmin() ## gives index of the minimum value in the tensor

tensor(0)

In [ ]:
torch.argmin(tensor_x)

tensor(0)

In [ ]:
tensor_x.argmax() ## gives index of the maximum value in the tesnsor,

tensor(99)

In [ ]:
torch.argmax(tensor_x)

tensor(99)

### Other Tensor operations:
1. Reshaping - changing shape of the tensor.
2. View - return a view of the input tensor of certain shape , but keep the same memory as the original tensor.
3. Stacking (horizontal, vertical) - combining multiple tesnors.
4. squeezing - removes all `1` dimension from tensor.
5. unsqueezing - adds a `1` dimension to a tensor.
6. Premute - return a view of the tensor with permuted/swapped in certain way.

In [ ]:
x = torch.arange(start=1, end=13)

In [ ]:
x, x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]), torch.Size([12]))

In [ ]:
# reshape - has to be comaptible with original size of the tensor.
x_reshape = x.reshape(2,6)
x_reshape

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

In [ ]:
# Change the view - here changing z changes x , because a view of a tensor shares the same memory as the original input
z = x.view(1, 12)
z, z.shape


(tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]),
 torch.Size([1, 12]))

In [ ]:
# the first element of the x and z is changed
z[:,0] = 5
x, z

(tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]))

In [ ]:
# stack tensors

x_stacked = torch.stack([x,x,x,x], dim=0) # stacks rows
x_stacked

tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [ ]:
x_stacked = torch.stack([x,x,x,x], dim=1) # stacks rows
x_stacked

tensor([[ 5,  5,  5,  5],
        [ 2,  2,  2,  2],
        [ 3,  3,  3,  3],
        [ 4,  4,  4,  4],
        [ 5,  5,  5,  5],
        [ 6,  6,  6,  6],
        [ 7,  7,  7,  7],
        [ 8,  8,  8,  8],
        [ 9,  9,  9,  9],
        [10, 10, 10, 10],
        [11, 11, 11, 11],
        [12, 12, 12, 12]])

In [ ]:
# squeeze tensor dimension - torch.sqeeze() - removes all single dimensions from a tensor

In [ ]:
x_reshape = x.reshape(1, 12)
print(f"previous tensor: {x_reshape}")
print(f"previous tensor shape: {x_reshape.shape}")

previous tensor: tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])
previous tensor shape: torch.Size([1, 12])


In [ ]:
x_squeeze = x_reshape.squeeze()
print(f"squeezed tensor: {x_squeeze}")
print(f"squeezed tensor shape: {x_squeeze.shape}")

previous tensor: tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
previous tensor shape: torch.Size([12])


In [ ]:
# unsqueeze tensor dimension - torch.unsqeeze() - adds single dimension to a tensor at given specific dimension.

In [ ]:
print(f"previous tensor: {x_squeeze}")
print(f"previous tensor shape: {x_squeeze.shape}")

x_unsqueezed = x_squeeze.unsqueeze(dim=0)

print(f"un_squeezed tensor: {x_unsqueezed}")
print(f"un_squeezed tensor shape: {x_unsqueezed.shape}")

previous tensor: tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
previous tensor shape: torch.Size([12])
un_squeezed tensor: tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])
un_squeezed tensor shape: torch.Size([1, 12])


In [ ]:
# permute - torch.permute() - rearranges the dimension of a tensor in a specified order.

In [ ]:
 x = torch.randn(1, 2, 3)
 x, x.size()

(tensor([[[-0.1009, -0.6039,  1.5722],
          [ 0.7990, -2.5069,  0.4780]]]), torch.Size([1, 2, 3]))

In [ ]:
torch.permute(x, (2, 1, 0)), torch.permute(x, (2, 1, 0)).size()

(tensor([[[-0.1009],
          [ 0.7990]],
 
         [[-0.6039],
          [-2.5069]],
 
         [[ 1.5722],
          [ 0.4780]]]), torch.Size([3, 2, 1]))

### Tensor indexing

In [ ]:
x = torch.arange(start=1, end=10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0][0][0]

tensor(1)

### Reproducibility

In [ ]:
random_tensor_A = torch.rand(size=(3,4))
random_tensor_B = torch.rand(size=(3, 4))

In [ ]:
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.0929, 0.0102, 0.9131, 0.2925],
        [0.4987, 0.4490, 0.6658, 0.8526],
        [0.2600, 0.5871, 0.5744, 0.4540]])
tensor([[0.7134, 0.3276, 0.6047, 0.3428],
        [0.8955, 0.2944, 0.0082, 0.2565],
        [0.8787, 0.9115, 0.7083, 0.5863]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

In [ ]:
random_tensor_C = torch.rand(size=(3,4))

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(size=(3, 4))

In [ ]:
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
